const views={home:document.getElementById('homeView'),booking:document.getElementById('bookingView'),confirm:document.getElementById('confirmView'),complete:document.getElementById('completeView'),lookup:document.getElementById('lookupView'),info:document.getElementById('infoView'),admin:document.getElementById('adminView')};
const STORAGE_KEY='genkikkoReservations';
const TIMES=['09:00','09:30','10:00','10:30','11:00','11:30','14:00','14:30','15:00','15:30','16:00','16:30'];
const MAX_PER_SLOT=3;
let draft=null, deferredPrompt=null;
function getReservations(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{return[]}}
function saveReservations(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[m])}
function showView(name){Object.values(views).forEach(v=>v.classList.remove('active'));(views[name]||views.home).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});document.getElementById('mainNav').classList.remove('open');if(name==='lookup')renderReservations();if(name==='admin')renderAdmin()}
window.showView=showView;
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>el.classList.remove('show'),2200)}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();showView(el.dataset.view)}));
document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('mainNav').classList.toggle('open'));
const isoToday=new Date().toISOString().split('T')[0];document.getElementById('visitDate').min=isoToday;document.getElementById('editDate').min=isoToday;
function slotCount(date,time,excludeId=null){return getReservations().filter(r=>r.id!==excludeId&&r.date===date&&r.time===time&&r.status!=='キャンセル').length}
function slotState(date,time,excludeId=null){const c=slotCount(date,time,excludeId);return c>=MAX_PER_SLOT?'full':c===MAX_PER_SLOT-1?'few':'ok'}
function renderTimeSlots(){const date=document.getElementById('visitDate').value,wrap=document.getElementById('timeSlots'),hidden=document.getElementById('visitTime');hidden.value='';if(!date){wrap.innerHTML='<div class="muted">先に受診日を選択してください。</div>';return}wrap.innerHTML=TIMES.map(t=>{const s=slotState(date,t),label=s==='full'?'×':s==='few'?'△':'○';return `<button type="button" class="slot-btn ${s}" data-time="${t}" ${s==='full'?'disabled':''}>${t}<small>${label}</small></button>`}).join('');wrap.querySelectorAll('.slot-btn:not(:disabled)').forEach(b=>b.addEventListener('click',()=>{wrap.querySelectorAll('.slot-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');hidden.value=b.dataset.time}))}
document.getElementById('visitDate').addEventListener('change',renderTimeSlots);renderTimeSlots();
document.querySelectorAll('[data-service]').forEach(btn=>btn.addEventListener('click',()=>{const service=btn.dataset.service;document.getElementById('serviceType').value=service;document.getElementById('bookingServiceBadge').textContent=service;document.getElementById('vaccinationField').classList.toggle('hidden',service!=='予防接種');showView('booking');renderTimeSlots()}));
function collectForm(){return{service:serviceType.value,date:visitDate.value,time:visitTime.value,name:patientName.value.trim(),kana:patientKana.value.trim(),birthDate:birthDate.value,visitType:visitType.value,phone:phone.value.trim(),symptom:symptom.value.trim(),vaccine:vaccineName.value}}
bookingForm.addEventListener('submit',e=>{e.preventDefault();draft=collectForm();if(!draft.time){toast('予約時間を選択してください');return}const rows=[['予約内容',draft.service],['受診日時',`${draft.date} ${draft.time}`],['お子さまのお名前',draft.name],['ふりがな',draft.kana],['生年月日',draft.birthDate],['受診区分',draft.visitType],['電話番号',draft.phone],['症状・相談内容',draft.symptom||'入力なし']];if(draft.service==='予防接種')rows.splice(2,0,['希望ワクチン',draft.vaccine||'未選択']);confirmDetails.innerHTML=rows.map(([a,b])=>`<dl class="confirm-row"><dt>${esc(a)}</dt><dd>${esc(b)}</dd></dl>`).join('');showView('confirm')});
editBooking.addEventListener('click',()=>showView('booking'));
confirmBooking.addEventListener('click',()=>{if(!draft)return;if(slotState(draft.date,draft.time)==='full'){toast('この時間枠は満席になりました');showView('booking');renderTimeSlots();return}const list=getReservations(),id='GK'+Date.now().toString().slice(-6),record={id,...draft,status:'予約済み',createdAt:new Date().toISOString()};list.unshift(record);saveReservations(list);reservationNumber.textContent=id;completeSummary.innerHTML=`<p><strong>${esc(record.service)}</strong></p><p>📅 ${esc(record.date)} ${esc(record.time)}</p><p>👤 ${esc(record.name)} さま</p>`;bookingForm.reset();draft=null;renderTimeSlots();showView('complete')});
function renderReservations(){const c=reservationList,list=getReservations();if(!list.length){c.innerHTML='<div class="empty-state">まだ予約はありません。<br><button class="text-btn" onclick="showView(\'home\')">WEB予約へ進む →</button></div>';return}c.innerHTML=list.map(r=>`<article class="reservation-card"><div class="reservation-top"><div><span class="status ${r.status==='キャンセル'?'cancel':''}">${esc(r.status)}</span><h3>${esc(r.service)}</h3></div><strong>${esc(r.date)} ${esc(r.time)}</strong></div><div class="reservation-meta"><span>予約番号：${esc(r.id)}</span><span>患者名：${esc(r.name)} さま</span><span>区分：${esc(r.visitType)}</span><span>電話：${esc(r.phone)}</span></div><div class="card-actions"><button class="outline-btn" onclick="showDetail('${r.id}')">問診・詳細</button>${!['キャンセル','診察完了'].includes(r.status)?`<button class="outline-btn" onclick="openEdit('${r.id}')">日時変更</button><button class="danger-btn" onclick="cancelReservation('${r.id}')">キャンセル</button>`:''}</div></article>`).join('')}
window.cancelReservation=id=>{if(!confirm('この予約をキャンセルしますか？'))return;saveReservations(getReservations().map(r=>r.id===id?{...r,status:'キャンセル'}:r));renderReservations();toast('予約をキャンセルしました')};
window.showDetail=id=>{const r=getReservations().find(x=>x.id===id);if(!r)return;detailBody.innerHTML=`<dl class="detail-grid"><dt>予約番号</dt><dd>${esc(r.id)}</dd><dt>日時</dt><dd>${esc(r.date)} ${esc(r.time)}</dd><dt>患者名</dt><dd>${esc(r.name)}（${esc(r.kana)}）</dd><dt>生年月日</dt><dd>${esc(r.birthDate)}</dd><dt>受診区分</dt><dd>${esc(r.visitType)}</dd><dt>診療内容</dt><dd>${esc(r.service)}${r.vaccine?' / '+esc(r.vaccine):''}</dd><dt>電話番号</dt><dd>${esc(r.phone)}</dd><dt>状態</dt><dd>${esc(r.status)}</dd></dl><h4>問診内容</h4><div class="detail-note">${esc(r.symptom||'入力なし')}</div>`;detailModal.classList.remove('hidden')};
closeDetail.addEventListener('click',()=>detailModal.classList.add('hidden'));detailModal.addEventListener('click',e=>{if(e.target===detailModal)detailModal.classList.add('hidden')});
window.openEdit=id=>{const r=getReservations().find(x=>x.id===id);if(!r)return;editId.value=id;editDate.value=r.date;populateEditTimes(r.date,r.time,id);editModal.classList.remove('hidden')};
function populateEditTimes(date,current,id){editTime.innerHTML=TIMES.map(t=>{const s=slotState(date,t,id),dis=s==='full'?'disabled':'',lab=s==='full'?' ×':s==='few'?' △':' ○';return `<option value="${t}" ${t===current?'selected':''} ${dis}>${t}${lab}</option>`}).join('')}
editDate.addEventListener('change',()=>populateEditTimes(editDate.value,'',editId.value));closeEdit.addEventListener('click',()=>editModal.classList.add('hidden'));editModal.addEventListener('click',e=>{if(e.target===editModal)editModal.classList.add('hidden')});
editForm.addEventListener('submit',e=>{e.preventDefault();const id=editId.value,date=editDate.value,time=editTime.value;if(slotState(date,time,id)==='full'){toast('その時間枠は満席です');return}saveReservations(getReservations().map(r=>r.id===id?{...r,date,time}:r));editModal.classList.add('hidden');renderReservations();toast('予約日時を変更しました')});
function renderAdmin(){let list=getReservations();const status=adminFilter.value,service=adminServiceFilter.value,date=adminDateFilter.value,q=adminSearch.value.trim().toLowerCase();if(status!=='all')list=list.filter(r=>r.status===status);if(service!=='all')list=list.filter(r=>r.service===service);if(date)list=list.filter(r=>r.date===date);if(q)list=list.filter(r=>`${r.name} ${r.kana} ${r.id}`.toLowerCase().includes(q));adminEmpty.classList.toggle('hidden',list.length!==0);adminTableBody.innerHTML=list.map(r=>`<tr><td><strong>${esc(r.date)}</strong><br>${esc(r.time)}</td><td>${esc(r.name)}<br><span class="muted">${esc(r.phone)}</span></td><td>${esc(r.service)}</td><td>${esc(r.visitType)}</td><td><span class="status ${r.status==='キャンセル'?'cancel':''}">${esc(r.status)}</span></td><td><div class="card-actions"><button class="outline-btn" onclick="showDetail('${r.id}')">詳細</button><select class="status-select" onchange="updateStatus('${r.id}',this.value)">${['予約済み','受付済み','診察中','診察完了','キャンセル'].map(s=>`<option ${r.status===s?'selected':''}>${s}</option>`).join('')}</select></div></td></tr>`).join('');const all=getReservations(),today=new Date().toISOString().split('T')[0],todayList=all.filter(r=>r.date===today);todayCount.textContent=todayList.filter(r=>r.status!=='キャンセル').length;waitingCount.textContent=all.filter(r=>['予約済み','受付済み'].includes(r.status)).length;doneCount.textContent=all.filter(r=>r.status==='診察完了').length;cancelCount.textContent=all.filter(r=>r.status==='キャンセル').length}
window.updateStatus=(id,status)=>{saveReservations(getReservations().map(r=>r.id===id?{...r,status}:r));renderAdmin();toast(`ステータスを「${status}」に変更しました`)};
['adminFilter','adminServiceFilter','adminDateFilter'].forEach(id=>document.getElementById(id).addEventListener('change',renderAdmin));adminSearch.addEventListener('input',renderAdmin);clearAdminFilters.addEventListener('click',()=>{adminFilter.value='all';adminServiceFilter.value='all';adminDateFilter.value='';adminSearch.value='';renderAdmin()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});installBtn.addEventListener('click',async()=>{if(!deferredPrompt){toast('iPhoneはSafariの共有メニューから「ホーム画面に追加」を選んでください');return}deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add('hidden')});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
